akka {
  loglevel = "INFO"
  stdout-loglevel = "WARNING"

  actor {
    provider = cluster

    # Allow jackson serialization , if needed fall back to java
    allow-java-serialization = off
    warn-about-java-serializer-usage = off

    serializers {
        jackson-cbor = "akka.serialization.jackson.JacksonCborSerializer"
      }

    serialization-bindings {
      "disIND.prototypeModel.model.AkkaSerializable" = jackson-cbor
    }
  }

  remote.artery {
    canonical.hostname = "127.0.0.1"
    canonical.hostname = ${?AKKA_HOSTNAME}
    canonical.port = 2551
    canonical.port = ${?AKKA_PORT}
    bind.hostname = "0.0.0.0"
    bind.port = 2551
    transport = tcp

    advanced {
      maximum-frame-size = 64 MiB
      maximum-frame-size = ${?AKKA_MAXIMUM_FRAME_SIZE}

      # 4 * 64 MiB bounds this reusable direct-buffer pool to roughly 256 MiB per JVM   
      buffer-pool-size = 4
      buffer-pool-size = ${?AKKA_BUFFER_POOL_SIZE}
    }
  }

  cluster {
    
    roles = ["worker"]
    seed-nodes = ["akka://disIND@127.0.0.1:2551"]
    downing-provider-class = "akka.cluster.sbr.SplitBrainResolverProvider"
    split-brain-resolver.active-strategy = keep-majority

    sharding {
      number-of-shards = 64

      # Least-shard allocation balances load across nodes automatically
      # This is critical for skewed datasets: re-balances hot shards
      # Needed to change and test with some other options too
      least-shard-allocation-strategy {
        rebalance-absolute-limit = 4
        rebalance-relative-limit = 0.1
      }

      # Rebalance check interval: redistribute shards when load imbalanced
      rebalance-interval = 10s
      passivate-idle-entity-after = 5 minutes
    }
  }
}

akka.serialization.jackson {
  jackson-modules += "disIND.streamBasedShardedDispatcher.serialization.RoaringBitmapJacksonModule"
}
